"""Initialize the complete LearnEnglish database schema."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2026_09_27_id_init_database'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Achievement')),
    sa.UniqueConstraint('code', name='uq_achievements_code')
    )
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['Category.id'], name=op.f('fk_Category_parent_id_Category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Category')),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_table('Scenario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('initial_message', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Scenario')),
    sa.UniqueConstraint('slug', name='uq_scenarios_slug')
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tag')),
    sa.UniqueConstraint('slug', name='uq_tags_slug')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.UnicodeText(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('lastest_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastest_request', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('VocabularyBook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_VocabularyBook')),
    sa.UniqueConstraint('slug', name='uq_vocabulary_books_slug')
    )
    op.create_table('AchievementUnlock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['Achievement.id'], name=op.f('fk_AchievementUnlock_achievement_id_Achievement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_AchievementUnlock_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_AchievementUnlock')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_achievement_unlocks_user_id_achievement_id')
    )
    op.create_table('DictionaryLookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_DictionaryLookup_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DictionaryLookup'))
    )
    op.create_index('dictionary_lookups_idx', 'DictionaryLookup', ['user_id', 'created_time'], unique=False)
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_attachments', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('response', sa.String(length=3000), nullable=True),
    sa.Column('response_attachments', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Feedback_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedback'))
    )
    op.create_index('feedback_idx', 'Feedback', ['user_id', 'type'], unique=False, postgresql_using='btree')
    op.create_table('Lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_provider', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], name=op.f('fk_Lesson_category_id_Category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], name=op.f('fk_Lesson_created_by_User'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], name=op.f('fk_Lesson_updated_by_User'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Lesson')),
    sa.UniqueConstraint('slug', name='uq_lessons_slug'),
    sa.UniqueConstraint('video_provider', 'video_id', name='uq_lessons_video_provider_video_id')
    )
    op.create_index('lessons_idx', 'Lesson', ['status', 'published_at'], unique=False)
    op.create_index('lessons_category_idx', 'Lesson', ['category_id', 'status'], unique=False)
    op.create_index('lessons_difficulty_idx', 'Lesson', ['difficulty', 'status'], unique=False)
    op.create_table('Notebook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Notebook_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Notebook')),
    sa.UniqueConstraint('user_id', 'name', name='uq_notebooks_user_id_name')
    )
    op.create_table('Notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Notification_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Notification'))
    )
    op.create_index('notifications_idx', 'Notification', ['user_id', 'is_read', 'created_time'], unique=False)
    op.create_table('Streak',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Streak_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Streak')),
    sa.UniqueConstraint('user_id', name='uq_streaks_user_id')
    )
    op.create_table('Token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.UnicodeText(), nullable=False),
    sa.Column('token_type', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Token_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Token')),
    sa.UniqueConstraint('token', name='uq_tokens_token')
    )
    op.create_table('UserPreferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_display', sa.String(), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_new_words', sa.Integer(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_UserPreferences_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserPreferences')),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('UserRole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.UnicodeText(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['User.email'], name=op.f('fk_UserRole_email_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserRole')),
    sa.UniqueConstraint('email', 'role', name='uq_user_roles_email_role')
    )
    op.create_table('VocabularyTopic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['VocabularyBook.id'], name=op.f('fk_VocabularyTopic_book_id_VocabularyBook'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_VocabularyTopic')),
    sa.UniqueConstraint('book_id', 'slug', name='uq_vocabulary_topics_book_id_slug')
    )
    op.create_table('Conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_Conversation_lesson_id_Lesson'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['Scenario.id'], name=op.f('fk_Conversation_scenario_id_Scenario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Conversation_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Conversation'))
    )
    op.create_table('FeedbackAttachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['Feedback.id'], name=op.f('fk_FeedbackAttachment_feedback_id_Feedback'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_FeedbackAttachment'))
    )
    op.create_index('feedback_attachment_idx', 'FeedbackAttachment', ['feedback_id'], unique=False, postgresql_using='btree')
    op.create_table('LessonProgress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('last_position_seconds', sa.Integer(), nullable=False),
    sa.Column('completion_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_percent >= 0 AND completion_percent <= 100', name=op.f('ck_LessonProgress_completion_percent_range')),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_LessonProgress_lesson_id_Lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_LessonProgress_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LessonProgress')),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_progress_user_id_lesson_id')
    )
    op.create_index('lesson_progress_idx', 'LessonProgress', ['user_id', 'last_watched_at'], unique=False)
    op.create_table('LessonSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_LessonSession_lesson_id_Lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_LessonSession_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LessonSession'))
    )
    op.create_table('LessonTag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_LessonTag_lesson_id_Lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LessonTag_tag_id_Tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LessonTag')),
    sa.UniqueConstraint('lesson_id', 'tag_id', name='uq_lesson_tags_lesson_id_tag_id')
    )
    op.create_table('PracticeSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('initial_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['VocabularyTopic.id'], name=op.f('fk_PracticeSession_topic_id_VocabularyTopic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_PracticeSession_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_PracticeSession'))
    )
    op.create_index('practice_sessions_user_status_idx', 'PracticeSession', ['user_id', 'status'], unique=False)
    op.create_table('Subtitle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('translation_vi', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_ms > start_ms', name=op.f('ck_Subtitle_end_ms_after_start_ms')),
    sa.CheckConstraint('start_ms >= 0', name=op.f('ck_Subtitle_start_ms_non_negative')),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_Subtitle_lesson_id_Lesson'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Subtitle')),
    sa.UniqueConstraint('lesson_id', 'sequence', name='uq_subtitles_lesson_id_sequence')
    )
    op.create_index('subtitles_idx', 'Subtitle', ['lesson_id', 'start_ms'], unique=False)
    op.create_table('LessonAnswer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['LessonSession.id'], name=op.f('fk_LessonAnswer_session_id_LessonSession'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtitle_id'], ['Subtitle.id'], name=op.f('fk_LessonAnswer_subtitle_id_Subtitle'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LessonAnswer')),
    sa.UniqueConstraint('session_id', 'subtitle_id', name='uq_lesson_answers_session_id_subtitle_id')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('translation_vi', sa.Text(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name=op.f('fk_Message_conversation_id_Conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Message'))
    )
    op.create_index('messages_idx', 'Message', ['conversation_id', 'created_time'], unique=False)
    op.create_table('Vocabulary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('word_type', sa.String(), nullable=True),
    sa.Column('ipa', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('definition_vi', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation_vi', sa.Text(), nullable=True),
    sa.Column('source_subtitle_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_subtitle_id'], ['Subtitle.id'], name=op.f('fk_Vocabulary_source_subtitle_id_Subtitle'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Vocabulary'))
    )
    op.create_index('vocabularies_idx', 'Vocabulary', [sa.literal_column('lower(word)'), 'word_type'], unique=True)
    op.create_index('vocabularies_word_idx', 'Vocabulary', ['word'], unique=False)
    op.create_table('ActivityEvent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('lesson_session_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name=op.f('fk_ActivityEvent_conversation_id_Conversation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name=op.f('fk_ActivityEvent_lesson_id_Lesson'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_session_id'], ['LessonSession.id'], name=op.f('fk_ActivityEvent_lesson_session_id_LessonSession'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_ActivityEvent_user_id_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name=op.f('fk_ActivityEvent_vocabulary_id_Vocabulary'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ActivityEvent'))
    )
    op.create_index('activity_events_idx', 'ActivityEvent', ['user_id', 'created_time'], unique=False)
    op.create_index('activity_events_type_idx', 'ActivityEvent', ['user_id', 'type', 'created_time'], unique=False)
    op.create_table('NotebookItem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('source_subtitle_id', sa.Integer(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['Notebook.id'], name=op.f('fk_NotebookItem_notebook_id_Notebook'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_subtitle_id'], ['Subtitle.id'], name=op.f('fk_NotebookItem_source_subtitle_id_Subtitle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name=op.f('fk_NotebookItem_vocabulary_id_Vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_NotebookItem')),
    sa.UniqueConstraint('notebook_id', 'vocabulary_id', name='uq_notebook_items_notebook_id_vocabulary_id')
    )
    op.create_table('PracticeProgress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personal_note', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_PracticeProgress_user_id_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name=op.f('fk_PracticeProgress_vocabulary_id_Vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_PracticeProgress')),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name='uq_practice_progress_user_id_vocabulary_id')
    )
    op.create_index('practice_progress_idx', 'PracticeProgress', ['user_id', 'status', 'next_review_at'], unique=False)
    op.create_table('PracticeSessionItem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_id', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['PracticeSession.id'], name=op.f('fk_PracticeSessionItem_session_id_PracticeSession'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name=op.f('fk_PracticeSessionItem_vocabulary_id_Vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_PracticeSessionItem')),
    sa.UniqueConstraint('session_id', 'order_num', name='uq_practice_session_items_session_order'),
    sa.UniqueConstraint('session_id', 'vocabulary_id', name='uq_practice_session_items_session_vocab')
    )
    op.create_table('VocabularyTopicWord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['VocabularyTopic.id'], name=op.f('fk_VocabularyTopicWord_topic_id_VocabularyTopic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name=op.f('fk_VocabularyTopicWord_vocabulary_id_Vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_VocabularyTopicWord')),
    sa.UniqueConstraint('topic_id', 'vocabulary_id', name='uq_vocabulary_topic_words_topic_id_vocabulary_id')
    )
    op.create_table('PracticeAttempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practice_progress_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('used_hint', sa.Boolean(), nullable=False),
    sa.Column('revealed_answer', sa.Boolean(), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['practice_progress_id'], ['PracticeProgress.id'], name=op.f('fk_PracticeAttempt_practice_progress_id_PracticeProgress'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_PracticeAttempt'))
    )
    op.create_index('practice_attempts_attempt_id_uq', 'PracticeAttempt', ['attempt_id'], unique=True)
    # ### end Alembic commands ###
    

def downgrade() -> None:
    op.drop_table('PracticeAttempt')
    op.drop_table('VocabularyTopicWord')
    op.drop_table('PracticeSessionItem')
    op.drop_table('PracticeProgress')
    op.drop_table('NotebookItem')
    op.drop_table('ActivityEvent')
    op.drop_table('Vocabulary')
    op.drop_table('Message')
    op.drop_table('LessonAnswer')
    op.drop_table('Subtitle')
    op.drop_table('PracticeSession')
    op.drop_table('LessonTag')
    op.drop_table('LessonSession')
    op.drop_table('LessonProgress')
    op.drop_table('FeedbackAttachment')
    op.drop_table('Conversation')
    op.drop_table('VocabularyTopic')
    op.drop_table('UserRole')
    op.drop_table('UserPreferences')
    op.drop_table('Token')
    op.drop_table('Streak')
    op.drop_table('Notification')
    op.drop_table('Notebook')
    op.drop_table('Lesson')
    op.drop_table('Feedback')
    op.drop_table('DictionaryLookup')
    op.drop_table('AchievementUnlock')
    op.drop_table('VocabularyBook')
    op.drop_table('User')
    op.drop_table('Tag')
    op.drop_table('Scenario')
    op.drop_table('Category')
    op.drop_table('Achievement')
