"""Initialize the complete schema at the existing database revision.

Revision ID: e1f2a3b4c5d6
Revises:
Create Date: 2026-09-27

This baseline consolidates migrations through e1f2a3b4c5d6. Databases already
at that revision skip it; fresh databases create the same tables directly.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon_url', sa.VARCHAR(), nullable=True),
    sa.Column('condition_type', sa.VARCHAR(), nullable=False),
    sa.Column('condition_value', sa.INTEGER(), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_achievements'),
    sa.UniqueConstraint('code', name='uq_achievements_code')
    )
    op.create_table('Category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['Category.id'], name='fk_categories_parent_id_categories', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_categories'),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_table('Scenario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=False),
    sa.Column('character_name', sa.VARCHAR(), nullable=True),
    sa.Column('system_prompt', sa.TEXT(), nullable=False),
    sa.Column('initial_message', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_scenarios'),
    sa.UniqueConstraint('slug', name='uq_scenarios_slug')
    )
    op.create_table('Tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tags'),
    sa.UniqueConstraint('slug', name='uq_tags_slug'),
    postgresql_ignore_search_path=False
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('lastest_login', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lastest_request', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('VocabularyBook',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_vocabulary_books'),
    sa.UniqueConstraint('slug', name='uq_vocabulary_books_slug')
    )
    op.create_table('AchievementUnlock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('achievement_id', sa.INTEGER(), nullable=False),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['Achievement.id'], name='fk_achievement_unlocks_achievement_id_achievements', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_achievement_unlocks_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_achievement_unlocks'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_achievement_unlocks_user_id_achievement_id')
    )
    op.create_table('DictionaryLookup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('source_url', sa.VARCHAR(), nullable=True),
    sa.Column('context_sentence', sa.TEXT(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_dictionary_lookups_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_dictionary_lookups')
    )
    op.create_index('dictionary_lookups_idx', 'DictionaryLookup', ['user_id', 'created_time'], unique=False)
    op.create_table('Feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'new'::character varying"), nullable=False),
    sa.Column('user_attachments', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('response', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('response_attachments', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('response_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_Feedback_user_id_User', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_Feedback')
    )
    op.create_index('feedback_idx', 'Feedback', ['user_id', 'type'], unique=False)
    op.create_table('Lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('video_provider', sa.VARCHAR(), nullable=False),
    sa.Column('video_id', sa.VARCHAR(), nullable=False),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('views_count', sa.INTEGER(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], name='fk_lessons_category_id_categories', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], name='fk_lessons_created_by_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], name='fk_lessons_updated_by_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_lessons'),
    sa.UniqueConstraint('slug', name='uq_lessons_slug'),
    sa.UniqueConstraint('video_provider', 'video_id', name='uq_lessons_video_provider_video_id'),
    postgresql_ignore_search_path=False
    )
    op.create_index('lessons_category_idx', 'Lesson', ['category_id', 'status'], unique=False)
    op.create_index('lessons_difficulty_idx', 'Lesson', ['difficulty', 'status'], unique=False)
    op.create_index('lessons_idx', 'Lesson', ['status', 'published_at'], unique=False)
    op.create_table('Notebook',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_notebooks_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_notebooks'),
    sa.UniqueConstraint('user_id', 'name', name='uq_notebooks_user_id_name')
    )
    op.create_table('Notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('action_url', sa.VARCHAR(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_notifications_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_notifications')
    )
    op.create_index('notifications_idx', 'Notification', ['user_id', 'is_read', 'created_time'], unique=False)
    op.create_table('Streak',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('current_streak', sa.INTEGER(), nullable=False),
    sa.Column('longest_streak', sa.INTEGER(), nullable=False),
    sa.Column('last_active_date', sa.DATE(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_streaks_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_streaks'),
    sa.UniqueConstraint('user_id', name='uq_streaks_user_id')
    )
    op.create_table('Token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('token_type', sa.INTEGER(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_tokens_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_tokens'),
    sa.UniqueConstraint('token', name='uq_tokens_token')
    )
    op.create_table('UserPreferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subtitle_display', sa.VARCHAR(), nullable=False),
    sa.Column('daily_goal_minutes', sa.INTEGER(), nullable=False),
    sa.Column('daily_new_words', sa.INTEGER(), nullable=False),
    sa.Column('reminder_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('reminder_time', postgresql.TIME(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_user_preferences_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_preferences'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('UserRole',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['User.email'], name='fk_user_roles_email_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_roles'),
    sa.UniqueConstraint('email', 'role', name='uq_user_roles_email_role')
    )
    op.create_table('VocabularyTopic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('order_num', sa.INTEGER(), nullable=False),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['VocabularyBook.id'], name='fk_vocabulary_topics_book_id_vocabulary_books', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_vocabulary_topics'),
    sa.UniqueConstraint('book_id', 'slug', name='uq_vocabulary_topics_book_id_slug')
    )
    op.create_table('Conversation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_conversations_lesson_id_lessons', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['Scenario.id'], name='fk_conversations_scenario_id_scenarios', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_conversations_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_conversations')
    )
    op.create_table('FeedbackAttachment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_url', sa.VARCHAR(), nullable=False),
    sa.Column('attachment_type', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['Feedback.id'], name='fk_FeedbackAttachment_feedback_id_Feedback', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_FeedbackAttachment')
    )
    op.create_index('feedback_attachment_idx', 'FeedbackAttachment', ['feedback_id'], unique=False)
    op.create_table('LessonProgress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('last_position_seconds', sa.INTEGER(), nullable=False),
    sa.Column('completion_percent', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_watched_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('completion_percent >= 0::numeric AND completion_percent <= 100::numeric', name='ck_learning_progress_completion_percent_range'),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_lesson_progress_lesson_id_lessons', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_lesson_progress_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_lesson_progress'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_progress_user_id_lesson_id')
    )
    op.create_index('lesson_progress_idx', 'LessonProgress', ['user_id', 'last_watched_at'], unique=False)
    op.create_table('LessonSession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('mode', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('correct_count', sa.INTEGER(), nullable=False),
    sa.Column('total_count', sa.INTEGER(), nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_lesson_session_lesson_id_lessons', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_lesson_session_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_lesson_session')
    )
    op.create_table('LessonTag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_lesson_tags_lesson_id_lessons', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name='fk_lesson_tags_tag_id_tags', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_lesson_tags'),
    sa.UniqueConstraint('lesson_id', 'tag_id', name='uq_lesson_tags_lesson_id_tag_id')
    )
    op.create_table('PracticeSession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('scope', sa.VARCHAR(), nullable=False),
    sa.Column('initial_mode', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('current_position', sa.INTEGER(), nullable=False),
    sa.Column('total_items', sa.INTEGER(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['VocabularyTopic.id'], name='fk_PracticeSession_topic_id_VocabularyTopic', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_PracticeSession_user_id_User', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_PracticeSession')
    )
    op.create_index('practice_sessions_user_status_idx', 'PracticeSession', ['user_id', 'status'], unique=False)
    op.create_table('Subtitle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('sequence', sa.INTEGER(), nullable=False),
    sa.Column('start_ms', sa.INTEGER(), nullable=False),
    sa.Column('end_ms', sa.INTEGER(), nullable=False),
    sa.Column('content_en', sa.TEXT(), nullable=False),
    sa.Column('translation_vi', sa.TEXT(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('end_ms > start_ms', name='ck_subtitles_end_ms_after_start_ms'),
    sa.CheckConstraint('start_ms >= 0', name='ck_subtitles_start_ms_non_negative'),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_subtitles_lesson_id_lessons', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_subtitles'),
    sa.UniqueConstraint('lesson_id', 'sequence', name='uq_subtitles_lesson_id_sequence')
    )
    op.create_index('subtitles_idx', 'Subtitle', ['lesson_id', 'start_ms'], unique=False)
    op.create_table('LessonAnswer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('subtitle_id', sa.INTEGER(), nullable=False),
    sa.Column('user_input', sa.TEXT(), nullable=False),
    sa.Column('accuracy_score', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['LessonSession.id'], name='fk_lesson_answer_session_id_lesson_session', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtitle_id'], ['Subtitle.id'], name='fk_lesson_answer_subtitle_id_subtitles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_lesson_answer'),
    sa.UniqueConstraint('session_id', 'subtitle_id', name='uq_lesson_answers_session_id_subtitle_id')
    )
    op.create_table('Message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('translation_vi', sa.TEXT(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='fk_messages_conversation_id_conversations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_messages')
    )
    op.create_index('messages_idx', 'Message', ['conversation_id', 'created_time'], unique=False)
    op.create_table('Vocabulary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('word_type', sa.VARCHAR(), nullable=True),
    sa.Column('ipa', sa.VARCHAR(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('definition_vi', sa.TEXT(), nullable=True),
    sa.Column('example_sentence', sa.TEXT(), nullable=True),
    sa.Column('example_translation_vi', sa.TEXT(), nullable=True),
    sa.Column('source_subtitle_id', sa.INTEGER(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_subtitle_id'], ['Subtitle.id'], name='fk_vocabularies_source_subtitle_id_subtitles', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_vocabularies')
    )
    op.create_index('vocabularies_idx', 'Vocabulary', [sa.literal_column('lower(word::text)'), 'word_type'], unique=True)
    op.create_index('vocabularies_word_idx', 'Vocabulary', ['word'], unique=False)
    op.create_table('ActivityEvent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=True),
    sa.Column('vocabulary_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_session_id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('xp_earned', sa.INTEGER(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='fk_activity_events_conversation_id_conversations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lesson.id'], name='fk_activity_events_lesson_id_lessons', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_session_id'], ['LessonSession.id'], name='fk_activity_event_lesson_session', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_activity_events_user_id_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name='fk_activity_events_vocabulary_id_vocabularies', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_activity_events')
    )
    op.create_index('activity_events_idx', 'ActivityEvent', ['user_id', 'created_time'], unique=False)
    op.create_index('activity_events_type_idx', 'ActivityEvent', ['user_id', 'type', 'created_time'], unique=False)
    op.create_table('NotebookItem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.INTEGER(), nullable=False),
    sa.Column('vocabulary_id', sa.INTEGER(), nullable=False),
    sa.Column('context_sentence', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source_subtitle_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['Notebook.id'], name='fk_notebook_items_notebook_id_notebooks', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_subtitle_id'], ['Subtitle.id'], name='fk_notebook_items_source_subtitle_id_subtitles', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name='fk_notebook_items_vocabulary_id_vocabularies', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_notebook_items'),
    sa.UniqueConstraint('notebook_id', 'vocabulary_id', name='uq_notebook_items_notebook_id_vocabulary_id')
    )
    op.create_table('PracticeProgress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('vocabulary_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('ease_factor', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('repetition_count', sa.INTEGER(), nullable=False),
    sa.Column('interval_days', sa.INTEGER(), nullable=False),
    sa.Column('next_review_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('personal_note', sa.TEXT(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_practice_progress_user_id_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name='fk_practice_progress_vocabulary_id_vocabularies', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_practice_progress'),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name='uq_practice_progress_user_id_vocabulary_id')
    )
    op.create_index('practice_progress_idx', 'PracticeProgress', ['user_id', 'status', 'next_review_at'], unique=False)
    op.create_table('PracticeSessionItem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('vocabulary_id', sa.INTEGER(), nullable=False),
    sa.Column('order_num', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_attempt_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['PracticeSession.id'], name='fk_PracticeSessionItem_session_id_PracticeSession', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name='fk_PracticeSessionItem_vocabulary_id_Vocabulary', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_PracticeSessionItem'),
    sa.UniqueConstraint('session_id', 'order_num', name='uq_practice_session_items_session_order'),
    sa.UniqueConstraint('session_id', 'vocabulary_id', name='uq_practice_session_items_session_vocab')
    )
    op.create_table('VocabularyTopicWord',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('vocabulary_id', sa.INTEGER(), nullable=False),
    sa.Column('order_num', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['VocabularyTopic.id'], name='fk_vocabulary_topic_words_topic_id_vocabulary_topics', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['Vocabulary.id'], name='fk_vocabulary_topic_words_vocabulary_id_vocabularies', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_vocabulary_topic_words'),
    sa.UniqueConstraint('topic_id', 'vocabulary_id', name='uq_vocabulary_topic_words_topic_id_vocabulary_id')
    )
    op.create_table('PracticeAttempt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practice_progress_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.VARCHAR(), nullable=False),
    sa.Column('response_ms', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('mode', sa.VARCHAR(), nullable=True),
    sa.Column('correct', sa.BOOLEAN(), nullable=True),
    sa.Column('used_hint', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('revealed_answer', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('submitted_answer', sa.TEXT(), nullable=True),
    sa.Column('attempt_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['practice_progress_id'], ['PracticeProgress.id'], name='fk_practice_attempt_practice_progress_id_practice_progress', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_practice_attempt')
    )
    op.create_index('practice_attempts_attempt_id_uq', 'PracticeAttempt', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('practice_attempts_attempt_id_uq', table_name='PracticeAttempt')
    op.drop_table('PracticeAttempt')
    op.drop_table('VocabularyTopicWord')
    op.drop_table('PracticeSessionItem')
    op.drop_index('practice_progress_idx', table_name='PracticeProgress')
    op.drop_table('PracticeProgress')
    op.drop_table('NotebookItem')
    op.drop_index('activity_events_type_idx', table_name='ActivityEvent')
    op.drop_index('activity_events_idx', table_name='ActivityEvent')
    op.drop_table('ActivityEvent')
    op.drop_index('vocabularies_word_idx', table_name='Vocabulary')
    op.drop_index('vocabularies_idx', table_name='Vocabulary')
    op.drop_table('Vocabulary')
    op.drop_index('messages_idx', table_name='Message')
    op.drop_table('Message')
    op.drop_table('LessonAnswer')
    op.drop_index('subtitles_idx', table_name='Subtitle')
    op.drop_table('Subtitle')
    op.drop_index('practice_sessions_user_status_idx', table_name='PracticeSession')
    op.drop_table('PracticeSession')
    op.drop_table('LessonTag')
    op.drop_table('LessonSession')
    op.drop_index('lesson_progress_idx', table_name='LessonProgress')
    op.drop_table('LessonProgress')
    op.drop_index('feedback_attachment_idx', table_name='FeedbackAttachment')
    op.drop_table('FeedbackAttachment')
    op.drop_table('Conversation')
    op.drop_table('VocabularyTopic')
    op.drop_table('UserRole')
    op.drop_table('UserPreferences')
    op.drop_table('Token')
    op.drop_table('Streak')
    op.drop_index('notifications_idx', table_name='Notification')
    op.drop_table('Notification')
    op.drop_table('Notebook')
    op.drop_index('lessons_idx', table_name='Lesson')
    op.drop_index('lessons_difficulty_idx', table_name='Lesson')
    op.drop_index('lessons_category_idx', table_name='Lesson')
    op.drop_table('Lesson')
    op.drop_index('feedback_idx', table_name='Feedback')
    op.drop_table('Feedback')
    op.drop_index('dictionary_lookups_idx', table_name='DictionaryLookup')
    op.drop_table('DictionaryLookup')
    op.drop_table('AchievementUnlock')
    op.drop_table('VocabularyBook')
    op.drop_table('User')
    op.drop_table('Tag')
    op.drop_table('Scenario')
    op.drop_table('Category')
    op.drop_table('Achievement')
    # ### end Alembic commands ###
