"""remove_definition_en_from_vocabularies

Revision ID: 213d4bfb5049
Revises: a9a39866ffb0
Create Date: 2026-07-12 00:21:19.556737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213d4bfb5049'
down_revision: Union[str, Sequence[str], None] = 'a9a39866ffb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'definition_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('definition_en', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
