"""add_lastest_request_field

Revision ID: 915828c4d922
Revises: 294e8f216608
Create Date: 2026-07-02 22:52:05.824862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915828c4d922'
down_revision: Union[str, Sequence[str], None] = '294e8f216608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastest_request', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastest_request')
    # ### end Alembic commands ###
