"""create feedback table

Revision ID: fcd02fc77104
Revises: d4f8a12c6e30
Create Date: 2026-07-19 15:58:07.800336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd02fc77104'
down_revision: Union[str, Sequence[str], None] = 'd4f8a12c6e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Feedback_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedback'))
    )
    op.create_index('feedback_idx', 'Feedback', ['user_id', 'type'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('feedback_idx', table_name='Feedback', postgresql_using='btree')
    op.drop_table('Feedback')
    # ### end Alembic commands ###
